-- MySQL Script generated by MySQL Workbench
-- Mon Nov 24 14:10:34 2014
-- Model: NBADB    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema nbadb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nbadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nbadb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `nbadb` ;

-- -----------------------------------------------------
-- Table `nbadb`.`team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nbadb`.`team` ;

CREATE TABLE IF NOT EXISTS `nbadb`.`team` (
  `name` CHAR(30) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nbadb`.`game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nbadb`.`game` ;

CREATE TABLE IF NOT EXISTS `nbadb`.`game` (
  `idgame` INT UNSIGNED NOT NULL,
  `awayTeam` CHAR(30) NOT NULL,
  `homeTeam` CHAR(30) NOT NULL,
  `gameDate` DATETIME NOT NULL,
  PRIMARY KEY (`idgame`),
  INDEX `awayTeam_idx` (`awayTeam` ASC),
  INDEX `homeTeam_idx` (`homeTeam` ASC),
  CONSTRAINT `awayTeam`
    FOREIGN KEY (`awayTeam`)
    REFERENCES `nbadb`.`team` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `homeTeam`
    FOREIGN KEY (`homeTeam`)
    REFERENCES `nbadb`.`team` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nbadb`.`boxscore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nbadb`.`boxscore` ;

CREATE TABLE IF NOT EXISTS `nbadb`.`boxscore` (
  `gameid` INT UNSIGNED NOT NULL,
  `teamname` CHAR(30) NOT NULL,
  `home` TINYINT(1) NOT NULL,
  `win` TINYINT(1) NOT NULL,
  `fgm` INT NULL DEFAULT 0,
  `fga` INT NULL DEFAULT 0,
  `tpm` INT NULL DEFAULT 0,
  `tpa` INT NULL DEFAULT 0,
  `ftm` INT NULL DEFAULT 0,
  `fta` INT NULL DEFAULT 0,
  `oreb` INT NULL DEFAULT 0,
  `dreb` INT NULL DEFAULT 0,
  `reb` INT NULL DEFAULT 0,
  `ast` INT NULL DEFAULT 0,
  `stl` INT NULL DEFAULT 0,
  `blk` INT NULL DEFAULT 0,
  `tov` INT NULL DEFAULT 0,
  `pf` INT NULL DEFAULT 0,
  `pts` INT NULL DEFAULT 0,
  PRIMARY KEY (`gameid`, `teamname`),
  INDEX `teamname_idx` (`teamname` ASC),
  CONSTRAINT `gameid`
    FOREIGN KEY (`gameid`)
    REFERENCES `nbadb`.`game` (`idgame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `teamname`
    FOREIGN KEY (`teamname`)
    REFERENCES `nbadb`.`team` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nbadb`.`player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nbadb`.`player` ;

CREATE TABLE IF NOT EXISTS `nbadb`.`player` (
  `idplayer` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `position` CHAR(2) NULL,
  PRIMARY KEY (`idplayer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nbadb`.`playerboxscore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nbadb`.`playerboxscore` ;

CREATE TABLE IF NOT EXISTS `nbadb`.`playerboxscore` (
  `gameid` INT UNSIGNED NOT NULL,
  `idplayer` INT NOT NULL,
  `starter` TINYINT(1) NULL,
  `minutes` INT NULL DEFAULT 0,
  `fgm` INT NULL DEFAULT 0,
  `fga` INT NULL DEFAULT 0,
  `tpm` INT NULL DEFAULT 0,
  `tpa` INT NULL DEFAULT 0,
  `ftm` INT NULL DEFAULT 0,
  `fta` INT NULL DEFAULT 0,
  `oreb` INT NULL DEFAULT 0,
  `dreb` INT NULL DEFAULT 0,
  `reb` INT NULL DEFAULT 0,
  `ast` INT NULL DEFAULT 0,
  `stl` INT NULL DEFAULT 0,
  `blk` INT NULL DEFAULT 0,
  `tov` INT NULL DEFAULT 0,
  `pf` INT NULL DEFAULT 0,
  `pam` INT NULL DEFAULT 0,
  `pts` INT NULL DEFAULT 0,
  `dnp` TINYINT(1) NULL,
  PRIMARY KEY (`gameid`, `idplayer`),
  INDEX `playername_idx` (`idplayer` ASC),
  CONSTRAINT `gameid0`
    FOREIGN KEY (`gameid`)
    REFERENCES `nbadb`.`game` (`idgame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `playername`
    FOREIGN KEY (`idplayer`)
    REFERENCES `nbadb`.`player` (`idplayer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
